#ifndef MODULES_H_
#define MODULES_H_

enum ModuleID {
    MODULE_STDOUT,
    MODULE_CONSUMER,
    MODULE_CONSUMER_TRY,
    MODULE_PRODUCER,
    MODULE_PRODUCER2,
    MODULE_LATENCY_TEST,
    MODULE_LATENCY_TEST_ECHO,
    NUM_MODULES
};

#endif
